account:
  cookie_file: cookies.json
search:
  keywords:
  - 三角洲行动
  max_videos_per_keyword: 200
  filter:
    sort: click
    duration: 0
    time_range:
      type: recent
      value: 3
  strategy:
    selection: random
    strict_title_match: false
    random_pool_size: 20
comment:
  enable_image: true
  texts:
  - 三角洲玩家一起玩👇
  images:
  - C:/Users/cccc1m/Pictures/7f6b0bd451f30cac84cd8342a24a916b.jpg
behavior:
  min_delay: 30.0
  max_delay: 40.0
  headless: false
  timeout: 30000
browser:
  path: C:/Program Files/Google/Chrome/Application/chrome.exe
  port: 0
captcha:
  max_count: 3
  quiet_minutes: 5
  warmup_minutes: 30
warmup:
  basic:
    duration_minutes: 30
    max_videos: 50
  behavior:
    watch_time_min: 20
    watch_time_max: 240
    random_pause: true
    pause_prob: 0.005
    random_scroll: true
    scroll_prob: 0.01
    view_comment: true
    view_comment_prob: 0.005
    random_like: true
    like_prob: 0.3
  comment:
    enable: false
    probability: 0.1
    type: template
  source: recommend
