# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app\\launcher_gui.py'],
    pathex=['app'],
    binaries=[],
    datas=[
        ('app\\web\\frontend-v2\\dist', 'web\\frontend-v2\\dist'),
        ('app\\web\\frontend-v2\\dist\\assets', 'web\\frontend-v2\\dist\\assets'),
        ('app\\core\\models_config.yaml', 'core'),
        ('app\\config.template.yaml', '.'),
        ('app\\license', 'license'),
        ('app\\main.py', '.'),
    ],
    hiddenimports=[
        'main',
        'web.app',
        'web.routers.instances_api',
        'web.routers.model_router_api',
        'web.routers.session_router',
        'web.routers.notification_api',
        'web.routers.auth_api',
        'web.routers.browser_router',
        'web.routers.config_api',
        'web.routers.file_api',
        'web.routers.log_api',
        'web.routers.module_router',
        'web.routers.task_api',
        'web.websocket.ws_handler',
        'core.config',
        'core.ai_manager',
        'core.ai_provider',
        'core.ai_adapters',
        'core.models_registry',
        'core.prompts',
        'core.slot',
        'core.notification_manager',
        'core.notifier',
        'core.captcha_tracker',
        'core.auth',
        'core.search',
        'core.comment',
        'core.history',
        'core.warmup',
        'core.video_detail',
        'core.context',
        'ai_center.model_router',
        'ai_center.validator',
        'ai_center.event_bus',
        'ai_center.state_machine',
        'ai_center.planner',
        'ai_center.dispatcher',
        'ai_center.executor',
        'ai_center.reporter',
        'modules.registry',
        'modules.browser_pool',
        'modules.auth_module',
        'modules.search_module',
        'modules.comment_module',
        'modules.warmup_module',
        'modules.ai_gen_module',
        'modules.ai_filter_module',
        'modules.history_module',
        'modules.captcha_module',
        'modules.config_module',
        'modules.notify_module',
        'modules.report_module',
        'modules.bot_module',
        'license.gui',
        'license.validator',
        'utils.logger',
        'utils.date_parser',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'starlette',
        'pydantic',
        'ttkbootstrap',
        'cryptography',
        'tkinter',
        'tkinter.messagebox',
        'playwright',
        'playwright.sync_api',
        'loguru',
        'yaml',
        'requests',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BiliBotLauncher_v3.10',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 无控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_info.txt',  # 添加版本信息
    icon=r'F:\AI+program\bili-bot\eap8r-x2i41-001.ico',
)
